services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: wordcloud
      POSTGRES_DATA: /var/lib/postgresql
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  wordcloud:
    image: wordcloud-core:latest
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8081"
    volumes:
      - shared-data:/app/upload-dir
    environment:
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=jdbc:postgresql://db:5432/wordcloud
      - STORAGE_LOCATION=/app/upload-dir
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_QUEUE="wordcloud"
      - RABBIT_MQ_EXCHANGE="772"
      - RABBIT_MQ_ROUTINGKEY="tagcloud"
  worker:
    image: wordcloud-worker:latest
    depends_on:
      - db
      - rabbitmq
    volumes:
      - shared-data:/app/upload-dir
    environment:
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=jdbc:postgresql://db:5432/wordcloud
      - STORAGE_LOCATION=/app/upload-dir
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_QUEUE="wordcloud"
      - RABBIT_MQ_EXCHANGE="772"
      - RABBIT_MQ_ROUTINGKEY="tagcloud"
  frontend:
    image: wordcloud-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - wordcloud
    environment:
      - API_URL=http://localhost:8081
volumes:
  shared-data: