server:
    port: ${PORT:8081}
spring:
    main:
        allow-bean-definition-override: true
    application:
        name: wordcloud
    datasource:
        password: ${DATASOURCE_PASSWORD}
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/wordcloud}
        username: ${DATASOURCE_USERNAME:postgres}
    flyway:
        clean-disabled: false
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    rabbitmq:
        host: ${RABBIT_MQ_HOST:localhost}
        port: 5672
        username: guest
        password: guest
        queue: ${RABBIT_MQ_QUEUE:my-queue}
        exchange: ${RABBIT_MQ_EXCHANGE:my-exchange}
        routingkey: ${RABBIT_MQ_ROUTINGKEY:my-routingkey}
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    storage:
        location: ${STORAGE_LOCATION}