server:
    port: ${PORT:8081}
spring:
    main:
        allow-bean-definition-override: true
    application:
        name: wordcloud
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/wordcloud}
        username: ${DB_USERNAME:postgres}
    flyway:
        clean-disabled: false
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    rabbitmq:
        host: ${MQ_HOST:localhost}
        port: 5672
        username: guest
        password: guest
        queue: ${MQ_QUEUE}
        exchange: ${MQ_EXCHANGE}
        routingkey: ${MQ_ROUTINGKEY}
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    storage:
        location: ${STORAGE_LOCATION:upload-dir}